/**
 * P9 #79 — WCAG 2.2 VPAT 2.5 INT PDF generator.
 * Maps a11y audit results to WCAG Success Criteria.
 * Enterprise tier only.
 */

export interface VpatOptions {
  productName: string;
  productVersion: string;
  contactEmail: string;
  companyName?: string;
  logo?: string;
  date?: string;
}

interface ScMapping {
  sc: string;
  name: string;
  level: 'A' | 'AA';
}

const SC_MAPPINGS: ScMapping[] = [
  { sc: '1.1.1', name: 'Non-text Content', level: 'A' },
  { sc: '1.3.1', name: 'Info and Relationships', level: 'A' },
  { sc: '1.4.3', name: 'Contrast (Minimum)', level: 'AA' },
  { sc: '1.4.11', name: 'Non-text Contrast', level: 'AA' },
  { sc: '2.1.1', name: 'Keyboard', level: 'A' },
  { sc: '2.1.2', name: 'No Keyboard Trap', level: 'A' },
  { sc: '2.4.3', name: 'Focus Order', level: 'A' },
  { sc: '2.4.6', name: 'Headings and Labels', level: 'AA' },
  { sc: '2.4.7', name: 'Focus Visible', level: 'AA' },
  { sc: '3.3.2', name: 'Labels or Instructions', level: 'A' },
  { sc: '4.1.2', name: 'Name, Role, Value', level: 'A' },
  { sc: '4.1.3', name: 'Status Messages', level: 'AA' },
];

type Conformance = 'Supports' | 'Partially Supports' | 'Does Not Support' | 'Not Applicable';

export function generateVpatHtml(
  a11yIssues: Array<{ type: string; message: string; impact?: string }>,
  opts: VpatOptions,
): string {
  const rows = SC_MAPPINGS.map((sc) => {
    const related = a11yIssues.filter((i) => mapIssueToSc(i.type) === sc.sc);
    let conformance: Conformance = 'Supports';
    let remarks = 'No issues found.';
    if (related.length > 0) {
      const critical = related.filter((i) => i.impact === 'critical' || i.impact === 'serious');
      if (critical.length > 0) {
        conformance = 'Does Not Support';
        remarks = critical.map((i) => i.message).join('; ');
      } else {
        conformance = 'Partially Supports';
        remarks = related.map((i) => i.message).join('; ');
      }
    }
    return `<tr><td>${sc.sc}</td><td>${sc.name}</td><td>${sc.level}</td><td>${conformance}</td><td>${esc(remarks)}</td></tr>`;
  }).join('');

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>VPAT 2.5 INT — ${esc(opts.productName)}</title>
<style>body{font-family:Inter,sans-serif;max-width:900px;margin:0 auto;padding:24px;color:#1D1D1F;background:#FAFAFA}
table{width:100%;border-collapse:collapse;margin:16px 0}th,td{border:1px solid #E5E7EB;padding:8px;text-align:left;font-size:13px}
th{background:#ECFDF5;font-weight:600}h1{font-size:20px}h2{font-size:16px;margin:24px 0 8px}</style></head>
<body>
${opts.logo ? `<img src="${esc(opts.logo)}" style="max-height:40px;margin-bottom:12px">` : ''}
<h1>Voluntary Product Accessibility Template (VPAT) 2.5 INT</h1>
<p><strong>Product:</strong> ${esc(opts.productName)} v${esc(opts.productVersion)}</p>
<p><strong>Company:</strong> ${esc(opts.companyName || '')}</p>
<p><strong>Date:</strong> ${esc(opts.date || new Date().toISOString().slice(0, 10))}</p>
<p><strong>Contact:</strong> ${esc(opts.contactEmail)}</p>
<h2>WCAG 2.2 Level A + AA Criteria</h2>
<table><thead><tr><th>SC</th><th>Criteria</th><th>Level</th><th>Conformance</th><th>Remarks</th></tr></thead><tbody>${rows}</tbody></table>
<footer style="margin-top:32px;color:#9CA3AF;font-size:11px">Generated by uxinspect</footer>
</body></html>`;
}

function mapIssueToSc(type: string): string | null {
  if (type.includes('alt') || type.includes('img')) return '1.1.1';
  if (type.includes('heading') || type.includes('structure')) return '1.3.1';
  if (type.includes('contrast')) return '1.4.3';
  if (type.includes('keyboard') || type.includes('trap')) return '2.1.1';
  if (type.includes('focus') && type.includes('order')) return '2.4.3';
  if (type.includes('focus') && type.includes('visible')) return '2.4.7';
  if (type.includes('label')) return '3.3.2';
  if (type.includes('aria') || type.includes('role')) return '4.1.2';
  return null;
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
